Repository appuio/component-airlock-microgateway, pull requests merged in 2025-09, with the labels that each got.

#8 Create `CiliumNetworkPolicy` when Cilium is installed
  component/resources.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/resources/airlock-microgateway/airlock-microgateway/02_resources/01_gateway_networkpolicies.yaml
  tests/resources.yml
Labels: enhancement

#9 Add support for deploying Gateway API CRDs in API group `x-openshift.microgateway.airlock.com`
  class/airlock-microgateway.yml
  class/defaults.yml
  component/airlock-xopenshift.jsonnet
  component/olm.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/olm/airlock-microgateway/airlock-microgateway/00_prerequisites/00_airlock_xopenshift/backendtlspolicies.x-openshift.microgateway.airlock.com.yaml
  tests/golden/olm/airlock-microgateway/airlock-microgateway/01_olm/10_operator_subscription.yaml
  tests/olm.yml
Labels: enhancement, bump:minor

#12 docs: Fix formatting in gateway listener guide
  docs/modules/ROOT/pages/how-tos/gateway-listener-manager.adoc
Labels: documentation
